/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        bg:         '#07070f',
        surface:    '#0f0f1a',
        surface2:   '#16162a',
        surface3:   '#1a1a2e',
        border:     '#1c1c2e',
        borderBright:'#272740',
        accent:     '#7c5cfc',
        accentHov:  '#8f72ff',
        accentDim:  '#7c5cfc1a',
        accentLite: '#7c5cfc33',
        green:      '#00d68f',
        greenDim:   '#00d68f1a',
        red:        '#ff4d6a',
        redDim:     '#ff4d6a1a',
        amber:      '#ffb347',
        amberDim:   '#ffb3471a',
        blue:       '#4da6ff',
        blueDim:    '#4da6ff1a',
        text:       '#e8e8f4',
        muted:      '#666688',
        dim:        '#333355',
      },
      fontFamily: {
        sans:  ['DM Sans', 'sans-serif'],
        syne:  ['Syne', 'sans-serif'],
        mono:  ['DM Mono', 'monospace'],
      },
      boxShadow: {
        glow:   '0 0 24px 0 #7c5cfc33',
        card:   '0 2px 12px 0 #00000033',
        cardHov:'0 4px 24px 0 #00000055',
        green:  '0 0 20px 0 #00d68f33',
        red:    '0 0 20px 0 #ff4d6a33',
      },
      backgroundImage: {
        grad:       'linear-gradient(135deg,#7c5cfc,#4da6ff)',
        gradGreen:  'linear-gradient(135deg,#00d68f,#00b07a)',
        gradRed:    'linear-gradient(135deg,#ff4d6a,#cc2244)',
        gradAmber:  'linear-gradient(135deg,#ffb347,#e07800)',
        gradSurface:'linear-gradient(135deg,#0f0f1a,#16162a)',
      },
      animation: {
        'fade-up':   'fadeUp .25s ease both',
        'scale-in':  'scaleIn .15s ease both',
        'slide-in':  'slideIn .2s ease both',
        'pulse-dot': 'pulseDot 2s ease infinite',
        'spin-slow': 'spin 2s linear infinite',
        'shimmer':   'shimmer 1.5s ease-in-out infinite',
      },
      keyframes: {
        fadeUp:   { from:{ opacity:'0', transform:'translateY(10px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        scaleIn:  { from:{ opacity:'0', transform:'scale(.95)' }, to:{ opacity:'1', transform:'scale(1)' } },
        slideIn:  { from:{ opacity:'0', transform:'translateX(-20px)' }, to:{ opacity:'1', transform:'translateX(0)' } },
        pulseDot: { '0%,100%':{ opacity:'.4' }, '50%':{ opacity:'1' } },
        shimmer:  { '0%':{ backgroundPosition:'200% 0' }, '100%':{ backgroundPosition:'-200% 0' } },
      },
      borderRadius: {
        xl2: '16px',
        xl3: '20px',
      },
    },
  },
  plugins: [],
};
